### ISSUE TITLE
execution thread

### ISSUE THREAD

**Issue by veontomo** [florina-muntenescu/DroidconMVVM#6]
Hi,
it seems that all actions are executed in the main thread even though the method bind() of the [MainActivity](https://github.com/florina-muntenescu/DroidconMVVM/blob/master/app/src/main/java/upday/droidconmvvm/MainActivity.java) states 
```
mSubscription.add(mViewModel.getGreeting()
                           .subscribeOn(Schedulers.computation())
                           .observeOn(AndroidSchedulers.mainThread())
                           .subscribe(this::setGreeting)
);
```
Could you confirm or disprove it?

**Comment by florina-muntenescu** [comment]
This was caused by the usage of a Subject from the main thread. 
I added a scheduler provider to the ViewModel that allows setting the thread on which the work with the data model happens. Check out the latest version of the code.

**Comment by veontomo** [comment]
Great! 
This way it is better.

**Comment by franciscojunior** [comment]
Hi, @florina-muntenescu !

Just wanted to confirm with you if the getSupportedLanguages() method call in:

```
mSubscription.add(mViewModel.getSupportedLanguages()
                                    .subscribeOn(Schedulers.computation())
                                    .observeOn(AndroidSchedulers.mainThread())
.subscribe(this::setLanguages));
```

is really using the computation thread to do its work. Because the just operator will create the Observable in the same thread it is being called on (which in this case will be the Android main thread), regardless of the subscribeOn operator call.  I could get it working in another thread if I use the `Observable.fromCallable` creator instead of using `Observable.just()` inside the DataModel.

I think I may be missing something. Thank you very much in advance for any guidance.

P.S.: Sorry if I'm posting in the wrong place. As I think my doubt is somewhat related to this issue, I tried to ask it here first. If you want, I can open another issue.

**Comment by florina-muntenescu** [comment]
@franciscojunior - yes, you were right. I just changed it to `Observable.fromCallable`.  Thanks!

**Comment by franciscojunior** [comment]
Thank you too, @florina-muntenescu ! For this project and all the many videos and articles you have produced which are helping me very much to understand RxJava and MVVM! :)

**Comment by florina-muntenescu** [comment]
@franciscojunior - happy to hear that! Thank you!
